// RiskCheckbox Page
export const RISKCHECKBOX_FETCHING = "RISKCHECKBOX_FETCHING";
export const RISKCHECKBOX_SUCCESS = "RISKCHECKBOX_SUCCESS";
export const RISKCHECKBOX_FAILED = "RISKCHECKBOX_FAILED";
export const RISKCHECKBOX_CLEAR = "RISKCHECKBOX_CLEAR";